PATH_MOVIE_LIST = "/api/v1/movies"
PATH_MOVIE = f"{PATH_MOVIE_LIST}/<movie_id>"
PATH_MOVIE_LIKES = f"{PATH_MOVIE_LIST}/<movie_id>/likes"
PATH_MOVIE_DISLIKES = f"{PATH_MOVIE_LIST}/<movie_id>/dislikes"

CHARACTER_LIMIT_DESCRIPTION = 300
CHARACTER_LIMIT_TITLE = 100

PROPERTY_TITLE = "title"
PROPERTY_DESCRIPTION = "description"
PROPERTY_RELEASE_YEAR = "release_year"
PROPERTY_DURATION_MINUTES = "duration_minutes"
PROPERTY_RATING = "rating"
