CHARACTER_LIMIT_DESCRIPTION = 300
CHARACTER_LIMIT_TITLE = 100
PROPERTY_TITLE = "title"
PROPERTY_DESCRIPTION = "description"
PROPERTY_RELEASE_YEAR = "release_year"
PROPERTY_DURATION_MINUTES = "duration_minutes"
PROPERTY_RATING = "rating"
